name: Op

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - uses: rokibhasansagar/slimhub_actions@main

      - name: build image and run docker
        run: |
          sudo apt install docker.io
          sudo apt install python3 python3-pip
          pip3 install -r requirements-cli.txt
          sudo docker build . -t mltb
          sudo docker run -p 80:80 -p 8080:8080 mltb
          
       - name: Loop workflow
         run: |
              git clone https://github.com/nanomltb2/mirror-leech-telegram-bot loop
              cd loop
              echo "1" >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              expect -c "
              spawn git push -f 
              expect \"main -> main\"
              set timeout -10
              interact"
